### ISSUE TITLE
Update on conda-forge

### ISSUE THREAD

**Issue by kthyng** [podaac/data-subscriber#108]
Hi again, I'm the person who put your package on conda-forge. Since the recipe can be built from pypi releases, the conda-forge bot is able to create updated recipes for your software as new releases come out. I had ignored some of these notifications for the past few months but finally opened one up yesterday. I had to update the recipe a bit to get some new requirements in, but now you have the [conda-forge version for 1.10.1](https://anaconda.org/conda-forge/podaac-data-subscriber). Hopefully the bot will revisit and make a new conda-forge release for your new release. I missed a few of the earlier versions. But, I have set up the conda-forge feedstock bot now so that it will try to automerge the new recipes as they come up, so hopefully everything will "just work"! I'll try to pay attention to the notifications as they come through, too. It would be good to have someone directly involved in your software on the recipe maintainer list too.

**Comment by kthyng** [comment]
Looks like the new version came through too! https://github.com/conda-forge/podaac-data-subscriber-feedstock/pull/7#issuecomment-1295203324

woohoo!

**Comment by mike-gangl** [comment]
Thanks that's fantastic! we will work to identify someone or some role to be placed on this. Great to see new versions come through, we will check when we release out next version (probably within the next few weeks!)

**Comment by kthyng** [comment]
Sounds good!
