### ISSUE TITLE
Access as a function

### ISSUE THREAD

**Issue by castelao** [podaac/data-subscriber#112]
Thanks for your time developing this package. Have you considered offering such functionalities as functions, so other packages could easily use them? I usually isolate the functionality in a high-level function and provide a command line interface on the top, such as in [OceanColor](https://github.com/castelao/OceanColor). One can use the command line defined on [line 19](https://github.com/castelao/OceanColor/blob/343de1c537f326d90f350dbaef3712781316b33b/OceanColor/cli.py#L19), or directly the `InRange` as in [line 40](https://github.com/castelao/OceanColor/blob/343de1c537f326d90f350dbaef3712781316b33b/OceanColor/cli.py#L40).

Any package that relies on accessing these datasets, such as the OceanColor package, would be able to simplify and rely on your `data-subscribe`'s functions.

**Comment by mike-gangl** [comment]
Thanks for your note! we've been so busy offering functionality that we haven't kept the code as modular as it could/should be. We will look at a way to separate out the functionality for use in other tools- it may be a combination of libraries (e.g. a generic podaac-py library).

**Comment by jinbow** [comment]
This will be very useful!

**Comment by castelao** [comment]
Thanks
