### ISSUE TITLE
Need to get your new requirement in for PyPI and conda-forge

### ISSUE THREAD

**Issue by kthyng** [podaac/data-subscriber#133]
Hi! I have been pinged about conda-forge trying to update your recipe. I added `packaging` to the conda-forge recipe (https://github.com/conda-forge/podaac-data-subscriber-feedstock/pull/9), but I am not familiar with poetry to know how to make sure that dependencies make it from your package into the PyPI release, which is currently not working. Any advice, or can you fix it?

**Comment by mike-gangl** [comment]
the recent release (1.13.0) had an issue that was just fixed in the 1.13.1 release.

As for moving forward, the only dependencies would be found in the pyproject.toml https://github.com/podaac/data-subscriber/blob/main/pyproject.toml#L14-L18

right now, we require: 
```
python = "^3.7"
requests = "^2.27.1"
tenacity = "^8.0.1"
packaging = "^23.0"
```
