### ISSUE TITLE
Scroll for result sizes > 2000

### ISSUE THREAD

**Issue by mgangl** [podaac/data-subscriber#15]
Subscriber wasn't written for massive bulk downloads in mind, so there is no concept of scrolling through large result sets.

Utilize the CMR scrolling mechanism to fetch listings of files, though this could be millions of files if the search criteria are large enough.

**Comment by ifenty** [comment]
What sets the 2000 file limit,  the page_size variable or is from cmr?

**Comment by mike-gangl** [comment]
CMR returns 2000 results. It **does** have a 'scroll' system available for larger queries. We just haven't implemented that yet but it's something we know we need to add for subscriber and the bulk download capabilities. the suggested work around has always been to use start/stop date ranges. This works well enough for daily/monthly/yearly datasets. This is really a pain for datasets in the hundreds of thousands of granules (a lot of the L2 data falls under this).

**Comment by frankinspace** [comment]
Latest recommendation is to use searchafter instead of scrolling:
https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#search-after
