### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by mgangl** [podaac/data-subscriber#17]
https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=6&t=1418

> Good evening!
> 
> We download a lot of data from PODAAC and occasionally something goes wrong partway through the download (real-world stuff like the a bad network connection the system going down at the wrong moment).
> 
> Does the cloud data subscriber script have mechanisms to deal with these cases? Ideally it should try to get the failed download again but quickly "give up" if the problem persists.
> 

Subscriber should be able to 'resume' during a download failure. Currently, if any of the downloads fail during a subscriber run, the subscriber "exits" without updating its last run, and the next time it runs, it will attempt to download all files from the previous, "failed" run, even if only one out of N files actually failed.

**Comment by mike-gangl** [comment]
Some more comments: 

What I’d really like is something like what ncftp has, which checks to see if I’ve already got a copy of each file in my download directory and only actually downloads if I don’t. (Or alternatively, I’m okay with overwriting identical existing files – it’s just electrons to me; you’re the ones paying for the big database and transfer cost!)

**Comment by skorper** [comment]
Related, we want to update the data subscriber to not re-download granules if the UMM-G revision date changes but the data content itself does not change. 

We can achieve this by looking at the checksum in CMR UMM-G `DataGranule -> ArchiveAndDistributionInformation -> find entry where name ends with .nc -> checksum -> value`, and comparing that with the checksum calculated on the local version of file.

Keep in mind the checksum can be either md5 or sha512. 

https://podaac.jpl.nasa.gov/Tutorial-Discovering-Data-File-Checksums-for-Cloud-based-Data

**Comment by frankinspace** [comment]
Rather than `find entry where name ends with .nc` it would be more robust to first get `RelatedUrls` with `Type`=`GET DATA`, grab the filename from `URL`, then use that filename to find the correct entry in `DataGranule -> ArchiveAndDistributionInformation`

**Comment by skorper** [comment]
We also want a `force` option to redownload regardless of checksum.

**Comment by mike-gangl** [comment]
'resume' now works by comparing checksums of existing files with search results- so no re-download occurs.
