### ISSUE TITLE
Issue with .netrc file 

### ISSUE THREAD

**Issue by mickymags** [podaac/data-subscriber#177]
I am attempting to use the podaac-data-subscriber tool to download data from podaac via command line interface. I am getting an error when I do so which I believe is related to the creation of the netrc file. 

The command I am entering in the Command Line Interface is as follows:

"""
podaac-data-downloader -c OPERA_L3_DSWX-HLS_V1 -d "C:\Users\micky\Documents\SERVIR\flood_mapping_intercomparison\case_studies\pk_jun_23\dswx_hls\scripted_access" -sd 2023-06-15T00:00:00Z -ed 2023-06-17T00:00:00Z -b="73.21022,28.82895,75.47604,33.360566"
"""

And the error I am getting is as follows: 

"""
[2024-10-22 14:05:36,091] {podaac_access.py:83} WARNING - There's no .netrc file or the The endpoint isn't in the netrc file
[2024-10-22 14:05:36,091] {podaac_data_downloader.py:389} ERROR - Uncaught exception occurred during execution.
Traceback (most recent call last):
  File "c:\users\micky\anaconda3\lib\site-packages\subscriber\podaac_data_downloader.py", line 387, in main
    run()
  File "c:\users\micky\anaconda3\lib\site-packages\subscriber\podaac_data_downloader.py", line 141, in run
    pa.setup_earthdata_login_auth(edl)
  File "c:\users\micky\anaconda3\lib\site-packages\subscriber\podaac_access.py", line 86, in setup_earthdata_login_auth
    manager.add_password(None, endpoint, username, password)
UnboundLocalError: local variable 'username' referenced before assignment
"""

I attempted to set up a _netrc file (I'm on windows) as per the instructions in the Github, but the instructions are unclear, so I made a .txt file and included my login credentials before saving it as a _netrc file. 

Thank you in advance. 

Best regards, 
Micky

**Comment by joshgarde** [comment]
> I attempted to set up a _netrc file (I'm on windows) as per the instructions in the Github, but the instructions are unclear, so I made a .txt file and included my login credentials before saving it as a _netrc file.

Hi Micky - so it sounds like you might've created the `_netrc` file incorrectly. May I know what text editor your using on Windows? If it's the built-in Notepad, you'll need to perform some specific steps to save it specifically as a `_netrc` instead of as `_netrc.txt`. Could you right-click and show the properties for the `_netrc` file?

Please do not post your _netrc file as it contains sensitive credentials.

**Comment by joshgarde** [comment]
This issue will be closed since it's not an issue with data-subscriber itself, but we can continue to diagnose your issue here
