### ISSUE TITLE
add new optional argument

### ISSUE THREAD

**Issue by jinbow** [podaac/data-subscriber#2]
Is it possible to add a new optional argument that allows users to search available datasets from CMR based on keywords and return short_names?

**Comment by mgangl** [comment]
this is a useful utility, but a little outside the scope of this tool. Granted we need the shortname for this to work, but there are other ways of getting it. perhaps we can make that a part of the README.

I'd defer to using a CMR API client like https://github.com/nasa/eo-metadata-tools/tree/master/CMR/python to do this work.

One can also use [search.earthdata.nasa.gov](https://search.earthdata.nasa.gov/search) or find shortnames from the [PO.DAAC portal](https://podaac.jpl.nasa.gov/).
