### ISSUE TITLE
data-subscriber fails when dataset has no real start date and end date

### ISSUE THREAD

**Issue by ifenty** [podaac/data-subscriber#40]
An ECCO dataset of ancillary files has no natural 'start date' and 'end date'.  users shouldn't be required to specify them to download.

```
$ podaac-data-subscriber -c ECCO_L4_ANCILLARY_DATA_V4R4  -d anc
WARN: No .update in the data directory. (Is this the first run?)
Downloaded: 0 files

Files Failed to download:0

CMR token successfully deleted
```

Oh, it also fails when I specify a start date and end date that spans the entire ECCO period:

```
$ podaac-data-subscriber -c ECCO_L4_ANCILLARY_DATA_V4R4  -d anc -sd 1990-01-01T00:00:00Z -ed 2021-01-01T01:01:01Z
NOTE: .update found in the data directory. (The last run was at 2022-01-27T20:07:48Z.)
Downloaded: 0 files

Files Failed to download:0

CMR token successfully deleted

```

**Comment by mike-gangl** [comment]
This actually looks like a different bug- you seem to have an existing ".update" file in your ./anc directory, which it's using to say when it last retrieved data. i wonder if you delete the .update file in that ./anc directory, and re-run with the start/end date will you get results? I think this goes back to using the same download directory for multiple runs (a totally valid use case we didn't develop for)

I'd also need to investigate if the suffix of those ancillary files are in the default suffix list --extensions

```
-e EXTENSIONS, --extensions EXTENSIONS
                       The extensions of products to download. Default is [.nc, .h5, .zip]
```

**Comment by ifenty** [comment]
unfortunately not.  even after deleting the anc directory and re-running I get the same results.

```
$rm -fr anc*
$podaac-data-subscriber -c ECCO_L4_ANCILLARY_DATA_V4R4  -d anc -sd 1990-01-01T00:00:00Z -ed 2021-01-01T01:01:01Z
NOTE: Making new data directory at anc(This is the first run.)
Downloaded: 0 files

Files Failed to download:0

CMR token successfully deleted
```

**Comment by mike-gangl** [comment]
thanks, i did a quick look and the files in that collection are of type 'tar.gz':

Granule Listing:
https://cmr.earthdata.nasa.gov/search/granules.json?echo_collection_id=C2096684707-POCLOUD

```
"href": "s3://podaac-ops-cumulus-protected/ECCO_L4_ANCILLARY_DATA_V4R4/ancillary_data_output_insitu_ECCO_V4r4.tar.gz"
```

We'll add the 'tar.gz' as a default type to the --extension parameter.
