### ISSUE TITLE
Download data by cycle and pass 

### ISSUE THREAD

**Issue by sureshshsv** [podaac/data-subscriber#41]
Instead of asking for data between DATE-1 and DATE-2 some users may want data for CYCLE-23 to CYCLE-26.  Expand subscriber to search/download by cycle as well.  This would really be helpful for JASON series missions.  Other users may want data by pass, too.  For missions that don't include pass and cycle appropriate warning messages have to be displayed.

**Comment by mike-gangl** [comment]
We will begin with cycle based downloads. if multiple passes are specified, only one cycle can be used.

**Comment by mike-gangl** [comment]
Closed. Will be available in 1.8.0 release. Cycles only, the "pass" based downloads are not added right now.
