### ISSUE TITLE
Changes to .update file

### ISSUE THREAD

**Issue by sureshshsv** [podaac/data-subscriber#42]
Say, user is changing the search parameters the update file might conflict and not download any files. If update file is present, then we need to compare it to the search parameters and make some decisions on whether we want to use the .update file or show a warning. For example -- say

"There are X number of files in the search parameter used , but all occur outside of the latest date in the .update date of YR-MO-DY.  Delete update file if you wish to proceed,” 

Other option is to add a flag that says, ignore .update file.

**Comment by mike-gangl** [comment]
Release 1.8.0 will introduce a new tool that allows 'data download' outside of a subscriber context. this will allow the bypassing of many '.update' file issues we've seen when using the subscriber as a 'bulk downloader'.

**Comment by mike-gangl** [comment]
Closed. Will be available with release of 1.8.0
