### ISSUE TITLE
Create better '.update' file name for allowing multiple subscribers to download to the same directory.

### ISSUE THREAD

**Issue by mike-gangl** [podaac/data-subscriber#44]
if a user uses the same directory (-d) for multiple collections, then there is no ability for it to know which collection the ".update" file belongs to. We should probably update this to use the collection name instead of the ".update" file name to ensure the same directory specified doesn't break functionality.

`.update_collectionshortname` file

_Originally posted by @mike-gangl in https://github.com/podaac/data-subscriber/issues/38#issuecomment-1023631008_

**Comment by ifenty** [comment]
I think this is a good idea

**Comment by mike-gangl** [comment]
Path forward:

* Subscriber  will look for .update__collection
* if found, use that and run as normal
  * after run, write an update ,update__collection
* if no .update__collection exists,
  * look for .update file
  * if .update file exists, use that and run as normal  
    * print warning that .update file is being used   
    * after run, write an update ,update__collection
  * if no .update file is used, run as normal (new run)
    * after run, write an update ,update__collection

**Comment by mike-gangl** [comment]
Closed. Will be available with release of 1.8.0
