### ISSUE TITLE
--limit option doesn't work for downloader

### ISSUE THREAD

**Issue by wveit** [podaac/data-subscriber#86]
Running the command `$ podaac-data-downloader -c GRACEFO_L2_CSR_MONTHLY_0060 -sd 2020-01-01T00:00:00Z -ed 2020-01-02T00:00:00Z -d ~/grace --limit 1 --verbose -e 00` causes 8 files to be downloaded even with `--limit 1`

The --limit option used to work, by setting the page_size in the CMR request. This worked because the downloader would only make 1 CMR request.

But now that the downloader/subscriber have implemented paging, setting page_size only results in multiple CMR requests.

Subscriber doesn't have --limit option, so it's not affected.

**Comment by mike-gangl** [comment]
this will be fixed in our next release- either 1.10.2 or 1.11.0
